language: java

sudo: required

python:
  - "3.6"

before_script:
  - sudo pip install httpbin
  - python -m httpbin.core &

# upload JaCoCo report to codecov
after_success:
- bash <(curl -s https://codecov.io/bash)

